### ISSUE TITLE
[UI] 인포 메인 / 뷰 생성

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS-Lab#3]
## ISSUE
- 인포 메인 화면 생성하기

## To-Do
- [x] infomain 전체 xml
- [x] infomain item xml
- [x] 뷰페이저 사용해 프래그먼트 화면 만들기
