### ISSUE TITLE
[FEAT] verification / OCR 온라인 인증서 발급 기능 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS-Lab#9]
## ISSUE
- verification / OCR 온라인 인증서 발급 기능 구현

## To-Do
- [x] CardFrame 커스텀뷰 구현
- [ ] 프리뷰 구현
- [ ] OCR API 연결
- [ ] bottom sheet dialog 구현
- [ ] 인증서 발급 결과 처리
